name: Deploy the redis to the server
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: kQRoyWxR3821CNTRL
          oauth-secret: tskey-client-kQRoyWxR3821CNTRL-m3eaQmBjzubdY631ATW5vbpA7XFeV5pT
          tags: tag:ci

      - run: ip ad sh