name: Deploy the redis to the server
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # - name: Tailscale
      #   uses: tailscale/github-action@v3
      #   with:
      #     oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      #     oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
      #     tags: autogroup:member

      # - run: ip ad sh

      - name: Setup SSH creds
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ vars.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa

      - run: |
          echo "${{ vars.json_file }}" >> json
          cat json
      # - run: ping -c4 100.84.66.128

      # - run: |
      #     ssh -o "StrictHostKeyChecking no" datafab@dialog-dev.taild1bdd.ts.net "
      #     echo 'hello world!' > test
      #     cat test
      #     "
