name: Deploy the redis to the server
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: kwkFTXnZFA21CNTRL
          oauth-secret: tskey-client-kwkFTXnZFA21CNTRL-MNh4yQQm3baotXzrMec8bazNSyi3Ahmg3
          tags: tag:ci

      - run: ip ad sh
