name: Deploy the redis to the server
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: k812z2XH7x11CNTRL
          oauth-secret: tskey-client-k812z2XH7x11CNTRL-eoahMeswqvbWAMFkpaSmvbywGMbAWKdP1
          tags: tag:ci

      - run: ip ad sh
